### ISSUE TITLE
When openning the ASCC-ipython_master.ipynb file with Anaconda, It occurs an error.

### ISSUE THREAD

**Issue by CNC-Not-Coder** [vanallenlab/2016-Mouw_ASCC#1]
As the title say, I follow the README file descripted, I installed the software Anaconda, and open the ipynb 
 file with the Jupyter notebook( ipython notebook previous), It occurs an error like "NotJSONError(Notebook does not appear to be JSON ....",  So, How to fix it ?

**Comment by CNC-Not-Coder** [comment]
It seems like that the ipynb file is incomplete.

**Comment by brendanreardon** [comment]
Hi @CNC-Not-Coder, 
Can you provide some more information? Perhaps a screenshot? How are you attempting to open the notebook?

From your terminal, you can type 
`ipython notbook`
Navigate your browser to localhost with the listed port, and then open the notebook.

**Comment by brendanreardon** [comment]
Hi @CNC-Not-Coder, I'm going to go ahead and close this since I haven't heard back from you. Feel free to reopen this issue.
